### ISSUE TITLE
Add Locales

### ISSUE THREAD

**Issue by Machou** [Sluimerstand/ProfessionShoppingList#202] opened 2024-10-16 17:58 UTC
Hello!

I've just discovered your addon and I'm very happy to be using it. Unfortunately, the translations are missing!

Could you add the localization files to translate the addon into our language?

Regards

**Comment by Sluimerstand** [comment] 2024-10-16 21:30
Duplicate of #137. I wasn't actually expecting someone to request this, but that just means I'll have to put some more priority on that! I'll see about getting this done soon, will be tracked via the original issue though. :)

**Closed by Sluimerstand** 2024-10-16 21:30 UTC
Labels: invalid
