### ISSUE TITLE
Warbank button to take out mats for oders

### ISSUE THREAD

**Issue by Addonman** [Sluimerstand/ProfessionShoppingList#201] opened 2024-10-16 17:28 UTC
Take mats out of warband bank for orders if you have mats since crafting for orders doesn't pull them out of there

**Comment by Sluimerstand** [comment] 2024-10-16 21:28
Duplicate of #182. I won't be implementing a feature like this, the reasoning is explained in the other issue. 11.0.5 will be here soon and make it so that crafting orders can make use of reagents stored in the Warbank.

**Closed by Sluimerstand** 2024-10-16 21:28 UTC
Labels: won't do, invalid
