### ISSUE TITLE
Error in Tweaks module at login

### ISSUE THREAD

**Issue by Gaviin1242** [Sluimerstand/ProfessionShoppingList#178] opened 2024-09-13 18:41 UTC
Using v11.0.2-012, this error is immediately thrown every time I log in:

18x ...aceProfessionShoppingList/modules/Tweaks.lua:261: attempt to index local 'f' (a nil value)
[string "@ProfessionShoppingList/modules/Tweaks.lua"]:261: in function `DisableHandyNotesAltRMB'
[string "@ProfessionShoppingList/modules/Tweaks.lua"]:35: in function `?'
[string "@ProfessionShoppingList/modules/Tweaks.lua"]:17: in function <...aceProfessionShoppingList/modules/Tweaks.lua:15>

Locals:
f = nil
f2 = Frame {
}
(*temporary) = "Frame"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'f' (a nil value)"

**Comment by Sluimerstand** [comment] 2024-09-13 21:05
I'm unable to reproduce this error on my end.
Does the error occur when PSL and HandyNotes (and BugSack + BugGrabber, if you use them) are the only addons enabled? I suspect another addon has an outdated library that's interfering.

**Comment by Sluimerstand** [comment] 2024-09-30 12:10
Closing this issue due to lack of user response.

**Closed by Sluimerstand** 2024-09-30 12:10 UTC
Labels: invalid

**Comment by Gaviin1242** [comment] 2024-09-30 22:59
Sorry I lost track and forgot to respond!  Yes, the error seems to only occur if HandyNotes is enabled along with this addon.

**Comment by Sluimerstand** [comment] 2024-10-01 11:37
I still cannot reproduce this issue when only PSL and HandyNotes are enabled. Are you sure you are testing with only those 2 addons enabled? (And BugSack/BugGrabber)

**Comment by Gaviin1242** [comment] 2024-10-01 23:08
Ah, I think I know what might be doing it.  I actually comment out a relatively small chunk of code in HandyNotes that hijacks the alt-right mouseclick event.  I want that action to put a TomTom waypoint, as it always had until HandyNotes came along and took it over.  So maybe removing that code causes some conflict with PSL?

Commented code is lines 473 through 502 in HandyNotes_HandyNotes.lua.

**Comment by Sluimerstand** [comment] 2024-10-02 00:31
Yes, manually altering HandyNotes' code is probably causing the issue. The PSL module it's conflicting with, actually does the same thing. It stops HandyNotes from hijacking the Alt+RMB hotkey. I made it because I got tired of having to manually adjust HandyNotes code every time they threw out an update.

You can disable PSL's HandyNotes tweak from the addon settings, or restore HandyNotes' original code. :)

**Comment by Gaviin1242** [comment] 2024-10-02 02:41
Lol, well then, sounds like you and I have the same annoyance with HandyNotes!  I just un-commented that code, and everything is working great now with no errors.  And alt-right click goes to TomTom.  All is right in the universe.  :)  Thanks, and sorry for the bother with this bug report!
