### ISSUE TITLE
Pull required reagents from Warbank

### ISSUE THREAD

**Issue by seabmn** [Sluimerstand/ProfessionShoppingList#182] opened 2024-09-22 15:33 UTC
Crafting orders need the reagents in your inventory not warbank.
the addon is great at building a list of reagents you need.
i believe it also can create an auctioning list (which is an addon i dont use)

what i think would be a great enahancement is when i open the warbank, to be able to press 1 button to pull all the items needed to fullfill tracked crafting orders from my warbank, so i can then quickly craft all of them.

**Comment by Sluimerstand** [comment] 2024-09-23 09:24
Hi @seabmn,
This is a feature that won't be implemented. The PTR Patch Notes for 11.0.5 have confirmed they will be fixing the issue then. Although we don't know exactly when that patch will be released, I don't see it as a worthwhile time investment to develop a feature that will be a bit tricky to get right (because reagent qualities are very fun) when a solution is already on the horizon. :)

**Closed by Sluimerstand** 2024-09-23 09:24 UTC
Labels: won't do
