### ISSUE TITLE
Error when adding Alchemist's Sturdy Mixing Rod

### ISSUE THREAD

**Issue by Bizzie1985** [Sluimerstand/ProfessionShoppingList#42] opened 2023-01-04 09:40 UTC
Date: 2023-01-04 10:35:16
ID: 4
Error occured in: Global
Count: 1
Message: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua line 417:
   attempt to compare nil with string
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:417:
      ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:356
   [string "=(tail call)"]: ?
   [string "=[C]"]: sort()
   [string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:330: SortData()
   [string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:613: SetData()
   [string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:192: pslReagents()
   [string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:350:
      ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:330
Locals:
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v9.1.BETA.5.8 (OneMawTime)
  AddonFactory, v10.0.009
  Altoholic, v10.0.009
  ArkInventory, v31012.04
  ArkInventoryRules, v31012
  ArkInventorySearch, v31012
  AskMrRobot, v120
  Auctionator, v10.0.28-2-gdd3dc71
  Auctioneer, v9.1.BETA.5.8 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.8 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.8 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.8 (OneMawTime)
  Bartender4, v4.14.4
  BetterWardrobe, v4.6.3
  BtWQuests, v2.26.0
  BtWQuestsDragonflight, v1.4
  CaerdonWardrobe, vv3.3.9
  Clique, vv3.4.12-release
  CraftSim, v1.5.7
  DataStore, v2022.12.11
  DataStoreAchievements, v2022.12.11
  DataStoreAgenda, v10.0.009
  DataStoreAuctions, v10.0.009
  DataStoreCharacters, v2022.12.11
  DataStoreContainers, v10.0.009
  DataStoreCrafts, v10.0.009
  DataStoreCurrencies, v10.0.009
  DataStoreGarrisons, v10.0.009
  DataStoreInventory, v10.0.009
  DataStoreMails, v2022.12.11
  DataStorePets, v10.0.009
  DataStoreQuests, v10.0.009
  DataStoreReputations, v10.0.009
  DataStoreSpells, v2022.12.11
  DataStoreStats, v10.0.009
  DataStoreTalents, v10.0.009
  DBMCore, v7293efb
  DBMStatusBarTimers, v7293efb
  DBMVPVEM, vfce23ce
  Details, v#Details.DF.Wrath.10337.148
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElkBuffBars, v2.7.0-206
  Enchantrix, v9.1.BETA.5.8 (OneMawTime)
  FishingBuddy, v1.19.4
  GatherMate2, v1.48.3
  Informant, v9.1.BETA.5.8 (OneMawTime)
  InstanceAchievementTracker, v4.8.0
  Mapster, v1.10.4
  MBB, v4.0.18
  MythicPlusTimer, v5.0.2
  Oilvl, v10.0.2
  Paste, v1.4.10
  PetTracker, v10.0
  PetTrackerJournal, v
  Plexus, vv2.5.6
  PointBlankSniper, v5.28
  Prat30, v3.9.15
  Prat30Libraries, v
  PremadeGroupsFilter, v3.4.1
  ProfessionShoppingList, vv10.0.2-016
  RareScanner, v10.0.2.13
  Rematch, v4.14.12
  Routes, vv1.7.4
  SlideBar, v9.1.BETA.5.8 (OneMawTime)
  SpartanUI, v6.2.13
  Stubby, v9.1.BETA.5.8 (OneMawTime)
  Titan, v6.00.10.100002
  TitanBag, v6.00.10.100002
  TitanClock, v6.00.10.100002
  TitanCurrenciesMulti, vv9.2.0
  TitanGold, v6.00.10.100002
  TitanLocation, v6.00.10.100002
  TitanLootType, v6.00.10.100002
  TitanPerformance, v6.00.10.100002
  TitanRepair, v6.00.10.100002
  TitanReputations, vv1.37
  TitanVolume, v6.00.10.100002
  TitanXP, v6.00.10.100002
  TomTom, v3.3.5-release
  TradeSkillMaster, vv4.12.15
  TradeSkillMasterAppHelper, vv4.12
  VenturePlan, v4.37
  VenturePlanMoreFollowers, v9
  WeakAuras, v5.3.3
  WorldBossTimers, vv1.9.8
  WorldQuestsList, v106
  WorldQuestTracker, vv10.0.2.460-Retail
  ZygorGuidesViewer, v9.0
  BlizRuntimeLib_enUS v10.0.2.100002 <none>
  (ck=a8a)

**Comment by Bizzie1985** [comment] 2023-01-04 21:28
Yes it did back then, even relogging etc didn't help fully. I cannot reproduce it anymore now however...

**Comment by Sluimerstand** [comment] 2023-01-05 08:49
That is understandable. When something is going wrong with adding a recipe like that, it usually means something before that went wrong, some wrong data got saved (or didn't get saved) to the saved variables. And then when you add a new recipe and it tries to recalculate everything, it breaks.

I've had this happen to me a few times as well, and I've had a previous report of this happening to someone else as well. If you do manage to reproduce this error at some point, please let me know! I will be reviewing the code sometime soon to check nothing is out of the ordinary, in the meantime I'll be closing this ticket since the issue is resolved and the error is not reproducible. :)

**Closed by Sluimerstand** 2023-01-05 08:49 UTC
Labels: bug
