### ISSUE TITLE
Bug: When no professions are known

### ISSUE THREAD

**Issue by nancikennedy** [Sluimerstand/ProfessionShoppingList#25] opened 2022-11-18 07:31 UTC
On Retail, with latest version. and nothing else loaded, the following error occurs upon logging in:

Message: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:413: attempt to index local 'icon' (a nil value)
Time: Thu Nov 17 23:27:47 2022
Count: 1
Stack: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:413: attempt to index local 'icon' (a nil value)
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:413: in function `pslSettings'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:623: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:368>

Locals: settings = Frame {
 0 = <userdata>
 name = "Profession Shopping List"
}
miniButton = <table> {
}
icon = nil
(*temporary) = <table> {
 NewLibrary = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/LibDBIcon-1.0/LibStub/LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/LibDBIcon-1.0/LibStub/LibStub.lua:46
 GetLibrary = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/LibDBIcon-1.0/LibStub/LibStub.lua:36
 libs = <table> {
 }
}
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "LibDataBroker_DataObjectCreated"
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:746
(*temporary) = SettingsPanel {
 0 = <userdata>
 GameTab = Button {
 }
 categoryLayouts = <table> {
 }
 RegisterCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:746
 RevertSettings = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:442
 ClosePanelButton = Button {
 }
 CheckTutorials = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:253
 OnShow = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:217
 Open = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:341
 GetSettingsCanvas = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:789
 AssignLayoutToCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:712
 CategoryList = Frame {
 }
 SearchBox = EditBox {
 }
 modified = <table> {
 }
 AddOnsTab = Button {
 }
 SetSecureAttributeResults = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:180
 ForEachCanvas = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:541
 Bg = Frame {
 }
 CallRefreshOnCanvases = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:580
 GetSecureAttributeResults = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:184
 OnLoad = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:55
 ExitWithoutCommit = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:305
 TransitionBackOpeningPanel = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:329
 FinalizeCommit = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:422
 SetCurrentCategorySettingsToDefaults = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:491
 GetAllCategories = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:742
 ExitWithCommit = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:318
 SetApplyButtonEnabled = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:556
 HasUnappliedSettings = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:528
 OnKeybindRebindSuccess = <function> define

**Comment by Sluimerstand** [comment] 2022-11-18 15:57
I wasn't able to reproduce this error, but I have updated the library that handles the minimap icon, which this error seems to come from.

Let me know if the latest update resolves this issue. If not, I'd love to get some more details on when this error occurs!

**Comment by nancikennedy** [comment] 2022-11-19 04:51
I updated to the latest version and I am stilling seeing an error close to the original above.

I tried re-enabling the minimap icon on the higher level chars who aren't having a problem, which made no difference. I then tried deleting my saved var files, and relogging. Still having the problem on many people, but it seems like it's trending towards those whose professions skills are super minimal (think "I unlocked all the exp skills I can" atm, but they're all at 1 skill essentially) or non-existent.

Also observed, when this error is present:
The /psl slash commands didn't work
PSL shows up in the Options:Addon list, but there's just a blank page where the settings should be.

The seems to be almost the same as the original...

Message: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:413: attempt to index local 'icon' (a nil value)
Time: Fri Nov 18 20:31:28 2022
Count: 1
Stack: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:413: attempt to index local 'icon' (a nil value)
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:413: in function `pslSettings'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:640: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:367>

Locals: settings = Frame {
 0 = <userdata>
 name = "Profession Shopping List"
}
miniButton = <table> {
}
icon = nil
(*temporary) = <table> {
 NewLibrary = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/LibDBIcon-1.0/LibStub/LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/LibDBIcon-1.0/LibStub/LibStub.lua:46
 GetLibrary = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/LibDBIcon-1.0/LibStub/LibStub.lua:36
 libs = <table> {
 }
}
(*temporary) = nil
(*temporary) = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "LibDataBroker_DataObjectCreated"
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:746
(*temporary) = SettingsPanel {
 0 = <userdata>
 GameTab = Button {
 }
 categoryLayouts = <table> {
 }
 RegisterCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:746
 RevertSettings = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:442
 ClosePanelButton = Button {
 }
 CheckTutorials = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:253
 OnShow = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:217
 Open = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:341
 GetSettingsCanvas = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:789
 AssignLayoutToCategory = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:712
 CategoryList = Frame {
 }
 SearchBox = EditBox {
 }
 modified = <table> {
 }
 AddOnsTab = Button {
 }
 SetSecureAttributeResults = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:180
 ForEachCanvas = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:541
 Bg = Frame {
 }
 CallRefreshOnCanvases = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:580
 GetSecureAttributeResults = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:184
 OnLoad = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:55
 ExitWithoutCommit = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:305
 TransitionBackOpeningPanel = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:329
 FinalizeCommit = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:422
 SetCurrentCategorySettingsToDefaults = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:491
 GetAllCategories = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:742
 ExitWithCommit = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:318
 SetApplyButtonEnabled = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:556
 HasUnappliedSettings = <function> defined @Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua:528
 OnKeybindRebindSuccess = <function> define

**Comment by Sluimerstand** [comment] 2022-11-19 12:49
Okay, I was able to re-create the error! I was using BugGrabber + BugSack to catch Lua errors, but those addons were actually preventing the error from occurring.
Turns out, the LibDBIcon library wasn't loading properly. For some reason the library as it is provided doesn't do that by default. And my bug grabbing addons also use LibDBIcon, and loaded it so that PSL could also use it.

This is now fixed, so the error should be resolved for you as well with v10.0.2-005.

**Comment by nancikennedy** [comment] 2022-11-19 13:33
Well, that totally explains why I couldn't get a consistent read on the problem. All the testing I was doing where I was seeing, I literally had disabled everything else including Bugsack/Grabber. I just didn't think to turn it off on the higher level people.

**Comment by Sluimerstand** [comment] 2022-11-19 13:36
It took me a while to try it without those as well, but it eventually clicked, haha. Can you confirm the error no longer appears with the latest version? :)

**Comment by nancikennedy** [comment] 2022-11-20 08:41
I can confirm this appears to be fixed. :)

**Closed** 2022-11-20 13:45 UTC
Labels: bug
